---
- hosts: mywebservers
  become: yes
  tasks: 
    - name: install java on ubuntu nodes
      apt: 
        name: "{{ myjavapackageforubuntu }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: install java on redhat nodes
      dnf:
        name: "{{ myjavapackageforredhat }}"
        state: present
      when: ansible_os_family == "RedHat"
